apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: env-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/rogerwoodford/environment-development.git'
      revision: main
      directories:
      {{- range .Values.core.namespaces }}
      - path: '{{ .name }}/*'
      {{- end }}
  template:
    metadata:
      name: '{{`{{path[0]}}-{{path.basename}}`}}'
      labels:
        environment: development
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{`{{path[0]}}`}}-project'
      source:
        repoURL: 'https://github.com/rogerwoodford/environment-development.git'
        targetRevision: main
        path: '{{`{{path}}`}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{`{{path[0]}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
